name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  easy_stepper: ^0.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  url_launcher: ^6.0.17
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/logo.jpg"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  # image: "assets/images/logo.png"
  # background_image: "assets/icons/native_splash.png"
  color_dark: "#ffffff"
  # image_dark: "assets/images/logo.png"
  #   # background_image_dark: "assets/images/splash_Screen_dark.png"
  android_gravity: center
  ios_content_mode: center
  # web: false
  fullscreen: true
  # android12: true
